### ISSUE TITLE
Bug with displaying avatars on shadow posts.

### ISSUE THREAD

**Issue by R3n001** [Dark1z/memberavatarstatus#20]
**Describe the bug :**   
When I move a topic, but leave a shadow in it's place, the extension appears to be unable to determine who made the last post, and shows the default user avatar, while also displaying some errors.
```
[phpBB Debug] PHP Notice: in file [ROOT]/ext/dark1/memberavatarstatus/core/avatar.php on line 203: Undefined index: topic_last_poster_avatar
[phpBB Debug] PHP Notice: in file [ROOT]/ext/dark1/memberavatarstatus/core/avatar.php on line 204: Undefined index: topic_last_poster_avatar_type
[phpBB Debug] PHP Notice: in file [ROOT]/ext/dark1/memberavatarstatus/core/avatar.php on line 205: Undefined index: topic_last_poster_avatar_width
[phpBB Debug] PHP Notice: in file [ROOT]/ext/dark1/memberavatarstatus/core/avatar.php on line 206: Undefined index: topic_last_poster_avatar_height
```

**To Reproduce :**   
1. Start with a basic phpBB setup with two forums.
2. Make a post in one forum
3. Use admin powers to move post and keep shadow topic in place (You might need a custom avatar for the error to occur)
4. See error in old forum.

**Expected behavior :**   
Moved topic and shadow topic have the user's profile picture

**Screenshots :**   
**This was taken when running 3.1.2, so the error is a bit different, but it's the same with 3.2.2.**
**The custom frames are not from a mod, they're part of the profile picture**
![ScreenShot_20210507150836](https://user-images.githubusercontent.com/77039240/117503957-56e02100-af47-11eb-8d2d-1c0dd3f39333.png)

**Device (please complete the following information) :**   
So, I'm guessing you mean the device running phpBB, which I don't really know what it is, so it's mostly guessing. What I do know is it's from iFastNet, with Linux and cPanel.
 - Device Type: Probably a virtual machine on a server
 - PHP: 7.4.16
 - phpBB: 3.3.3
 - OS: Linux
 - Browser: Firefox (Well, actually Waterfox, but it's basically Firefox 78 ESR)
 - Extension Version: 3.2.2

**Additional context :**   
The thread appears fine on the homepage, only when going to the forum does it show the error.
I moved the thread when using version 3.1.2 of the extension, and updated to 3.2.2 to see if that fixed anything, but it doesn't appear to have.

**Comment by Dark1z** [comment]
Thanks @R3n001 ,

I'll have a look into it,
this issue will be resolved in next release.

Best regards 👍
