### ISSUE TITLE
User online status stuck always showing.

### ISSUE THREAD

**Issue by R3n001** [Dark1z/memberavatarstatus#21]
(I finally got around to trying 3.2.4 build since I decided to jump to phpBB 3.3.4 today. Was going to wait for full stable release, but decided not to.)

**Describe the bug :**   
The circle showing the online status of the user always shows, no matter how the extension is configured.

**To Reproduce :**   
Set "Online Status Enable" to "No"

**Expected behavior :**   
The online status of users doesn't get showed

**Screenshots :**   
![ScreenShot_20210601175706](https://user-images.githubusercontent.com/77039240/120396026-eccb5980-c303-11eb-8736-26943dcbf639.png)

**Device (please complete the following information) :**   

 - Device Type: Probably a virtual machine on a server
 - PHP: 7.4.16
 - phpBB: 3.3.4
 - OS: Linux
 - Browser: Firefox
 - Extension Version: 3.2.4

**Comment by Dark1z** [comment]
@R3n001 ,

Thanks for the report,
I'll check this & make an appropriate update.

Best regards 👍
